name: movie-rating-daily

on:
  workflow_dispatch:
  schedule:
   - cron: '11 5 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          jupyter nbconvert --to notebook --execute 2_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_inference_pipeline.ipynb

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add movies.csv
          git commit -m "Update movies.csv [skip ci]" || echo "No changes to commit"
          git push
