name: movie-rating-daily

on:
  workflow_dispatch:
  schedule:
   - cron: '11 5 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          jupyter nbconvert --to notebook --execute 2_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_inference_pipeline.ipynb

- name: Push commit
  on: push
  permissions:
    contents: write
  jobs:
    report:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Commit report
          run: |
            git config --global user.name 'your-username'
            git config --global user.email 'your-username@users.noreply.github.com'
            git add movies.csv
            git commit -am "Automated report"
            git push