name: movie-rating-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python workflows
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          jupyter nbconvert --to notebook --execute 2_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_inference_pipeline.ipynb
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"
      
          git checkout -b "$branch_name"
      
          git add movies.csv
      
          git commit -m "Update CSV file"
      
          git push origin "$branch_name"
      
          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main
      
          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"