name: movie-rating-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python workflows
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          jupyter nbconvert --to notebook --execute 2_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_inference_pipeline.ipynb

      - name: Push updated movies.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add movies.csv
          git commit -m "Update movies.csv [Automated]"
          git push
